### ISSUE TITLE
Do not suggest to enable bundle in test env

### ISSUE THREAD

**Issue by garak** [EasyCorp/easy-doc-bundle#5]
You only need this in dev, don't you?

**Comment by javiereguiluz** [comment]
You are right. However, fixing this issue would create more problems. Let me explain:

The Symfony Standard edition contains this exact line in the kernel:

```php
if (in_array($this->getEnvironment(), ['dev', 'test'])) {
```

But it doesn't contain a line to enable bundles only in `dev`.

So, my reasoning is:

1) If you have experience with Symfony, you know what to do. You'll create a section for `dev` (or you already have created it) or don't care about this.
2) If you don't have much experience with Symfony, telling you that the bundle must be enabled in `dev` only complicates things: should I remove `test` in the original AppKernel? Should I create a new array for `dev` bundles? Should I copy/paste the provided code as it is or should I tweak it a bit? (because in my AppKernel I see `dev` and `test` but this bundle wrongly tells me only `dev`), etc.

**Comment by garak** [comment]
Take a closer look: https://github.com/symfony/symfony-standard/blob/master/app/AppKernel.php#L26

**Comment by javiereguiluz** [comment]
😱 😵 😱 😵 😱 😵 😱 😵 😱 😵 😱 😵 😱 😵 😱 😵

**Comment by javiereguiluz** [comment]
@garak fixed in 6174f66  I wasn't aware of this, so thank you for letting me know!
