### ISSUE TITLE
Make the Bootstrap "scrollspy" plugin work

### ISSUE THREAD

**Issue by javiereguiluz** [EasyCorp/easy-doc-bundle#6]
We use Bootstrap v4 alpha and we try to use [the scrollspy plugin](https://v4-alpha.getbootstrap.com/components/scrollspy/) but **it doesn't work**.

The idea is that the left sidebar items should be highlighted when you click on any of them or when you scroll the page up/down. Could any Bootstrap expert help us here? Thanks!

**Comment by stof** [comment]
The issue is that you apply ``data-spy=scroll`` on an element which is *not* the body, but this element does not seem to have a fixed height and does not seem to be the scroll container. See https://v4-alpha.getbootstrap.com/components/scrollspy/#requires-relative-positioning

I think you need to apply it on the ``<body>`` instead

**Comment by javiereguiluz** [comment]
Closing it as fixed by #12.
